version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: erp_db
    environment:
      POSTGRES_DB: ${DB_NAME_DEV:-erp_hospitalar_dev}
      POSTGRES_USER: ${DB_USER_DEV:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DEV:-468215973}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp-network

  backend:
    build: ./backend
    container_name: erp_backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_USER: ${DB_USER_DEV:-postgres}
      DB_PASSWORD: ${DB_PASSWORD_DEV:-468215973}
      DB_NAME: ${DB_NAME_DEV:-erp_hospitalar_dev}
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - erp-network

  frontend:
    build: ./frontend
    container_name: erp_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  postgres_data: